version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
    open-pull-requests-limit: 3

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      security:
        applies-to: security-updates
        patterns: ["*"]
      minor-and-patch:
        applies-to: version-updates
        update-types: [minor, patch]
        patterns: ["*"]
    open-pull-requests-limit: 3
